src/db.rs, src/page_store/mod.rs, src/page_store/page_txn.rs, src/table.rs, src/tree.rs
`Guard` holds the underlying resources. `PageTxn` holds the mutable transaction state. `PageTxn` also holds a `Guard` reference.
=> Split mutable and immutable txn state

src/page_store/page_file/file_builder.rs, src/page_store/page_file/file_reader.rs, src/page_store/page_file/info_builder.rs, src/page_store/page_file/mod.rs, src/page_store/page_file/types.rs
closes #67
- return file_info when file_builder::finish() to avoid addition disk read
- test recovery from folder and fix bug
=> page_store: refine file_info retrieve method 

src/page_store/jobs/gc.rs, src/table/mod.rs, src/table/tree.rs
The benefit is that we can now create a `PageRewriter` before creating a `PageStore`.
=> Decouple tree operations from the page store

src/env/mod.rs, src/env/photon.rs, src/env/stdenv.rs, src/page_store/manifest.rs, src/page_store/page_file/file_builder.rs, src/page_store/page_file/mod.rs, src/page_store/page_txn.rs, src/page_store/recover.rs
closes #153
- switch current manifest to new file during restart to avoid open-as-append
- add open_dir and cache parent directory to sync file metadata change
=> page_store: remove OpenOption::append and PositionalReader::sync_all

src/page/sorted_page.rs, src/tree/mod.rs
This will be used to fix some problems about root split.
=> Refactor sorted page split to return left and right iterators

Cargo.toml, bin/tools/Cargo.toml
The tools using different version cause
```
thread 'photonio-worker/0' panicked at 'cannot access a scoped thread local variable without calling `set` first', /home/robi/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/scoped-tls-1.0.1/src/lib.rs:168:9
stack backtrace:
0: std::panicking::begin_panic
at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:588:12
1: scoped_tls::ScopedKey<T>::with
at /home/robi/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/scoped-tls-1.0.1/src/lib.rs:168:9
2: photonio_uring::runtime::worker::spawn
at /home/robi/.cargo/git/checkouts/photonio-4d2b22930312944b/b32132b/photonio-uring/src/runtime/worker.rs:163:5
3: <photondb::env::photon::Photon as photondb::env::Env>::spawn_background
```
=> *: update photonio version in tools

src/page_store/strategy/mod.rs
=> page_store: skip compute decline rate of empty page file

src/tree/mod.rs
The underlying page store assumes that the mapping between page addresses and page ids is fixed.
However, the `reconcile_split_root()` will associate the original page chain with another page id. To address this problem, this PR refactors the root split and will not reuse any existing pages anymore.
=> Avoid changing the id of existing pages on root split

photondb/src/tree/mod.rs
We can not retry writes on the root because we split the root without updating its epoch.
=> Fix write on the root

photondb/src/page_store/version.rs
The test blocks the CI for too long. Ref: #249 
@w41ter You can enable it again when it works fine in CI.
=> ignore buffer_set_concurrent_update test

photondb/src/lib.rs, photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/jobs/gc.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/page_txn.rs, photondb/src/page_store/recover.rs
fixes #175
due to #175, it's better disable direct_io as default
=> page_store: make `use_direct_io` configurable in options

photondb/Cargo.toml, photondb/src/raw/mod.rs
closes #271
mainly port from sled, using quickcheck to generate get/del/put/restart ops and compare with memory Btreemap
=> test: add btreemap compare test

photondb/src/page_store/jobs/reclaim.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_txn.rs, photondb/src/tree/mod.rs
Iterator in table entries is not easy to solved because of lifetime annotation in the codebase.
I would like to start to delete unnecessary lifetime annotation in struct definition so that it is easier and more clear to reason about the lifetime of data structure without sacrifices the safety and performance.
This PR deletes lifetime annotation in `Guard`.
=> delete reference in Guard

photondb/src/page_store/jobs/reclaim.rs
fix panic found by @w41ter, introduced by #338
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Literal { len: 37, src_len: 426, dst_len: 0 }', photondb/src/page_store/page_file/[compression.rs:23](http://compression.rs:23/):18
stack backtrace:
0: rust_begin_unwind
at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/[panicking.rs:556](http://panicking.rs:556/):5
1: core::panicking::panic_fmt
at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14
2: core::result::unwrap_failed
at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/[result.rs:1785](http://result.rs:1785/):5
3: core::result::Result<T,E>::unwrap
at …
```
=> page_store: fix reclaim panic due read with wrong len

photondb/src/page_store/page_file/file_builder.rs, photondb/src/page_store/page_file/map_file_builder.rs, photondb/src/page_store/page_file/map_file_reader.rs, photondb/src/page_store/page_file/types.rs
closes #350
Fix panic when restarting the DB after one map file is generated.
This change:
- Add additional checksum / compression bits to MapFile's footer 
- Generate partial file's FileMeta from MapFile footer
So when read a page from partial file, it will using paritial file' FileMeta(which is consist with MapFile) to read data MapFile.
=> page_store: fix compression / checksum in partial file metadata

photondb-tools/src/bench/workloads.rs
Tiny fix a problem that run "two random bench but get 100% found" problem
For example, If we run with option:
```
-b 'fillrandom,readrandom'
```
It will run "fillrandom" first,  then run "readrandom" base on the previous result, readrandom should meet some NotFound key but it got "reads:1000000 founds:1000000"
=> tools: fix two random bench_ops has the same seed

photondb-tools/src/bench/store/photondb.rs, photondb-tools/src/bench/util.rs, photondb/src/lib.rs, photondb/src/page_store/cache.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_file/file_reader.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/stats.rs
- In desired, Cache will auto-cal the shard count by 32MiB per shard, but the current code is wrong only have one shard
- Port Rocksdb est_value_size advise logic to bench to warn in --db-stats when cache_estimated_entry_charge value is not suitable
- Let `cache_file_reader_capacity` can be configurated in option
run the randomread in the same dataset 2000000 keys with the same seed: 
`bench -t 1 -b readrandom --db /home/robi/testp341914 --num 2000000 --db-stats --key-rand-dist=uniform --seed-base 1669892707258583`
before this pr:(+ change cache_capacity to the same 128MiB)
`PageCacheStats: lookup_hit: 7008096, lookup_miss: 3924009, hit_rate: 64.10564113681674%, insert: 3924009, active_evict: 0, passive_evict: 3896485`
after 
`PageCacheStats: lookup_hit: 7820292, lookup_miss: 3111813, …
=> page_store: fix wrong default cache shard count & port est_value_size advisor

photondb-tools/src/bench/mod.rs, photondb-tools/src/bench/store/mod.rs, photondb-tools/src/bench/store/photondb.rs, photondb-tools/src/bench/util.rs, photondb-tools/src/bench/workloads.rs
Current Photon Env's `pread` impl is block and sync (in tokio), it's better use sync api as default
With the same data size 2000k and the same seed to random read: (read_in_files: 9998582
| tokio  | uring | std |
| ------------- | ------------- | ------------- |
|  54138.19850250811 ops/sec  | 88755.64525782471 ops/sec  | 131970.66758061736 ops/sec |
=> tools: change bench default env to std

photondb/src/lib.rs, photondb/src/tree/mod.rs
Fix situation that:
```
Root - Node1
```
append write Node1, then full & split node1, split will add delta to root, and consolidate root, but it seems no chance to trigger root to split.
=> tree: try split parent after node splitted

photondb-tools/src/bench/mod.rs, photondb-tools/src/bench/store/photondb.rs, photondb-tools/src/bench/util.rs, photondb/src/lib.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_file/compression.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/stats.rs, scripts/benchmark.sh
1. Set `cache_strict_capacity_limit=true`, so we should see some operation fail with `Error::MemoryLimit` instead of OOM(in desired)
2. Support enable or disable compression with bench arg, default disable
3. Output min/max/avg in bench tools and benchmark.sh result
4. add stall cnt oupt in benchmark.sh result
=> tools: set cache_strict_capacity_limit=true for bench & refine output info

photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/jobs/reclaim.rs, photondb/src/page_store/manifest.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_file/file_builder.rs, photondb/src/page_store/page_file/map_file_builder.rs, photondb/src/page_store/page_file/map_file_reader.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/page_file/types.rs, photondb/src/page_store/page_txn.rs, photondb/src/page_store/recover.rs
... and use map file as the output format, the staled codes related to page files will be removed later.
Close #387, close #390.
=> page_store: map file support dealloc pages

photondb-tools/src/bench/store/photondb.rs, photondb/src/page_store/cache/clock.rs, photondb/src/page_store/cache/lru.rs, photondb/src/page_store/page_file/mod.rs
-  change hash fn to fnv and cal with file_id + offset to reduce collision on bucket(find_pointer still have high cost in fillrandom flamegraph
-  disable prepopulate_cache_on_flush again, prepopulate_cache_on_flush seen help cache hit rate, but let flush slower, at last it make lower thoughput
- enlarge IO_BUFF
=> page_store,tools: using fnv hash & disable prepopulate as default

photondb/src/page_store/cache/clock.rs, photondb/src/page_store/cache/lru.rs, photondb/src/page_store/cache/mod.rs, photondb/src/page_store/jobs/cleanup.rs, photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/page_file/mod.rs
Pages may accessible after flush "as dealloc page", so this PR move active evict_page to cleanup file phase
=> page_store: move evict cache from flush to cleanup file phase

photondb/src/page_store/cache/clock.rs, photondb/src/page_store/cache/lru.rs, photondb/src/page_store/cache/mod.rs, photondb/src/page_store/page_file/cache.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/page_txn.rs, photondb/src/tree/mod.rs
Port RocksDB's cache priority to lru implement and let the inner page be inserted as High Priority.
run readrandom (page_size=16k, cache_size=512Mib, reserve 50% for high priority)
before
```
readrandom   :        17.8 micros/op 56026 ops/sec, 713.9 seconds, 40000000 operations; 22.9 MB/s  (reads:40000000 founds:40000000)
Percentiles_Read : P50: 17 ms, P75: 19 ms, P99: 25 ms, P99.9: 29 ms, P99.99: 33 ms, Min: 2 ms, Max: 26623 ms, AVG: 17.825 ms
TreeStats_success: read: 40000000, write: 0, split_page: 0, reconcile_page: 0, consolidate_page: 0, read_bytes: 17120000000, write_bytes: 0
TreeStats_conflict: read: 0, write: 0, split_page: 0, reconcile_page: 0, consolidate_page: 0
WritebufStats: read_in_buf: 0, read_in_files: 319116755, read_file_bytes: 1008701466235, read_hit_rate: 0.00%, …
```
=> page_store: support priority in lru_cache
