photondb/photondb

src/options.rs, src/page/base.rs, src/page/iter.rs, src/page/sorted_page.rs, src/page_store/error.rs, src/page_store/page_txn.rs, src/tree.rs
Start page transaction on-demand.
=> Fix some tree txn methods

src/lib.rs, src/table.rs, src/tree.rs, src/util/atomic.rs, src/util/mod.rs
Uses some atomic counter to collection transaction statistics.
=> Add util module and tree statistics

Cargo.lock, Cargo.toml, src/page_store/meta.rs, src/page_store/mod.rs
=> page_store: add defination of VersionEdit

src/page_store/pagefile/file_builder.rs, src/page_store/pagefile/file_reader.rs, src/page_store/pagefile/mod.rs
=> page_store: add definition of page_file builder and reader

src/page_store/manifest.rs, src/page_store/mod.rs
=> page_store: add manifest definition

Cargo.lock, Cargo.toml, src/page_store/page_file/file_builder.rs, src/page_store/page_file/file_reader.rs, src/page_store/page_file/info_builder.rs, src/page_store/page_file/mod.rs, src/page_store/page_file/types.rs
closes #52, closes #53, closes #54
=> page_store: impl file_reader to support read file_meta and page

src/page_store/manifest.rs
=> page_store: impl base read / write for manifest file

src/page_store/page_file/file_builder.rs, src/page_store/page_file/file_reader.rs, src/page_store/page_file/info_builder.rs, src/page_store/page_file/mod.rs, src/page_store/page_file/types.rs
=> page_store: support read page_file via direct io

src/page_store/page_txn.rs, src/tree/txn.rs
Simplify the `PageTxn` with more strict semantics.
=> Add replace_page interface

src/lib.rs, src/options.rs, src/page_store/mod.rs, src/store.rs, src/table.rs, src/tree/mod.rs, src/util/atomic.rs
Remove the `Table`/`RawTable` things and only focus on the "raw" interfaces for now.
=> Refactor module options and add a store interface

src/page_store/mod.rs, src/table/mod.rs
The original implementation use `futures::executor::block_on()` when dropping the page store, which may block the underlying runtime execution.
=> Add an async close method and a simple unit test

src/lib.rs, src/page_store/page_txn.rs, src/tree/mod.rs
=> Fix split page and split root

Cargo.toml, src/lib.rs, src/tree/mod.rs, src/tree/options.rs
=> Fix inner page consolidation

Cargo.toml
=> Update photonio to fix bugs

photondb/src/tree/mod.rs
=> Consolidate all delta pages on rewrite

photondb/src/tree/mod.rs
=> Specify page kind explicitly

photondb-tools/src/bench/benchmark.rs, photondb-tools/src/bench/mod.rs
- add yield after put to give schedule chance for flusher
- fix histogram display and add opt to control table_stats display
- add random read/write (each thread so some percent r/w)
- support control running time by duration
=> tools: refine bench & support ReadRandomWriteRandom

photondb/src/page_store/page_table.rs, photondb/src/page_store/recover.rs
=> Fix page table recovery

photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/jobs/mod.rs, photondb/src/page_store/jobs/reclaim.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/strategy/mod.rs
=> Destinguish garbage collection and space reclamation

photondb/src/tree/page.rs
=> Fix leaf and inner iter rewind

photondb/src/page_store/page_file/file_reader.rs, photondb/src/page_store/page_file/mod.rs
=> page_store: fix read empty data block

photondb/src/std.rs
ref #304
workaround loop when std env meet pending to let us can test other function
=> env: workround spin_loop when std env meet async pending

photondb/src/page_store/page_file/file_builder.rs, photondb/src/page_store/page_file/map_file_builder.rs, photondb/src/page_store/page_file/mod.rs
=> page_store: add map file builder

photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/jobs/reclaim.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_file/file_builder.rs, photondb/src/page_store/page_file/file_reader.rs, photondb/src/page_store/page_file/map_file_builder.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/page_file/types.rs, photondb/src/page_store/page_table.rs, photondb/src/page_store/page_txn.rs, photondb/src/page_store/version.rs
=> page_file: add map file meta

photondb/Cargo.toml, photondb/src/error.rs, photondb/src/lib.rs, photondb/src/page_store/cache.rs, photondb/src/page_store/error.rs, photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/jobs/reclaim.rs, photondb/src/page_store/mod.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/page_txn.rs, photondb/src/page_store/recover.rs, photondb/src/raw/mod.rs
=> page_store: add rough clock_cache

photondb/src/error.rs, photondb/src/page_store/error.rs, photondb/src/page_store/write_buffer.rs
=> page_store: forbid put that entry size larger than write_buffer_capacity

photondb/src/page_store/cache.rs
=> page_store: fix add overflow in read_cache

photondb/src/page/base_page.rs, photondb/src/page_store/page_txn.rs, photondb/src/tree/mod.rs, photondb/src/tree/stats.rs
=> Skip the first split delta on rewrite

photondb/Cargo.toml, photondb/src/page_store/page_file/file_reader.rs, photondb/src/page_store/page_file/mod.rs
=> page_store: replace moka to cache.rs for file_reader_cache

photondb/src/page_store/page_txn.rs
=> fix assert fail when return too_large_size error

photondb/src/page_store/jobs/flush.rs, photondb/src/page_store/jobs/reclaim.rs, photondb/src/page_store/manifest.rs, photondb/src/page_store/page_file/cache.rs, photondb/src/page_store/page_file/file_builder.rs, photondb/src/page_store/page_file/file_reader.rs, photondb/src/page_store/page_file/mod.rs, photondb/src/page_store/page_txn.rs, photondb/src/page_store/recover.rs
remove unnecessary unwrap/expect in page_files and manifest.
PS: sync fail still keep panic
=> page_store: throws IO error instead of unwrap 
